strategies: []
  # - strategy_path: src.strategies.choch.strategy:ChangeOfCharacterStrategy
  #   config_path: src.strategies.choch.strategy:ChangeOfCharacterStrategyConfig
  #   config:
  #     log_commands: True
  #     log_events: False
actors:
  - actor_path: src.strategies.choch.actors.choch_detector_v2:ChangeOfCharacterDetectorV2
    config_path: src.strategies.choch.actors.choch_detector_v2:ChangeOfCharacterDetectorV2Config
    config:
      log_data: True
      instrument_ids:
        # crypto
        - BTCUSDT-PERP.BINANCE_FUTURES
        # - DOGEUSDT-PERP.BINANCE_FUTURES
        # - XAGUSDT-PERP.BINANCE_FUTURES
  - actor_path: src.strategies.choch.actors.swing_detector:SwingDetector
    config_path: src.strategies.choch.actors.swing_detector:SwingDetectorConfig
    config:
      log_data: True
      period: 30
      use_wicks: False
      instrument_ids:
        # crypto
        - BTCUSDT-PERP.BINANCE_FUTURES
        # - DOGEUSDT-PERP.BINANCE_FUTURES
        - XAGUSDT-PERP.BINANCE_FUTURES
        # - TSLAUSDT-PERP.BINANCE_FUTURES
        # - LTCUSDT-PERP.BINANCE_FUTURES
        # - SOLUSDT-PERP.BINANCE_FUTURES
        # - SUIUSDT-PERP.BINANCE_FUTURES
        # - TRXUSDT-PERP.BINANCE_FUTURES
        # - XRPUSDT-PERP.BINANCE_FUTURES
