strategies:
  - strategy_path: src.strategies.swing_bos.reversal_strategy:SwingBosReversalStrategy
    config_path: src.strategies.swing_bos.reversal_strategy:SwingBosReversalStrategyConfig
    config:
      client_id: swing-reversal-strategy
      bar_type_timedelta: 1m
      log_commands: False
      log_events: False
actors:
  - actor_path: src.strategies.data.actors.markets:MarketsActor
    config_path: src.strategies.data.actors.markets:MarketsActorConfig
    config:
      client_id: markets-actor
      bar_type_historical: 30-MINUTE-LAST-INTERNAL
      bar_type_live: 5-MINUTE-LAST-INTERNAL
      markets_data_history: 100
      use_wicks: True
      markets:
        ASIA:
          tz: Asia/Hong_Kong
          open_time_hour: 8
          open_time_minute: 30
          color: "#6C5CE7"
        LONDON:
          tz: Europe/London
          open_time_hour: 8
          open_time_minute: 0
          color: "#3498DB"
        NY/PRE:
          tz: America/New_York
          open_time_hour: 8
          open_time_minute: 30
          break_type: secondary
          color: "#F8C471"
        NY:
          tz: America/New_York
          open_time_hour: 9
          open_time_minute: 30
          color: "#F39C12"
        NY/POST:
          tz: America/New_York
          open_time_hour: 16
          open_time_minute: 0
          break_type: secondary
          color: "#CA6F1E"
      blackout_window:
        start_weekday: 4
        start_hour: 16
        start_minute: 0
        end_weekday: 6
        end_hour: 18
        end_minute: 0
  - actor_path: src.strategies.data.actors.bars_sync:BarSyncronizerActor
    config_path: src.strategies.data.actors.bars_sync:BarSyncronizerActorConfig
    config:
      client_id: bars-sync-actor
      bar_type_specs:
        - 1-MINUTE-LAST-EXTERNAL
        - 5-MINUTE-LAST-INTERNAL@1-MINUTE-EXTERNAL
        - 30-MINUTE-LAST-INTERNAL@1-MINUTE-EXTERNAL
      instrument_ids:
        # crypto
        - BTCUSDT-PERP.BINANCE_FUTURES
        - XRPUSDT-PERP.BINANCE_FUTURES
        # metals
        - XAGUSDT-PERP.BINANCE_FUTURES
      historical_data_timedelta: 1d
      log_data: False
  - actor_path: src.strategies.data.actors.telegram:TelegramActor
    config_path: src.strategies.data.actors.telegram:TelegramActorConfig
    config:
      client_id: telegram-actor
      log_data: True
